# Generated by Django 2.1.3 on 2018-11-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('user_name', models.CharField(blank=True, max_length=30, null=True)),
                ('user_id', models.IntegerField(unique=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('authorized', models.BooleanField(default=False)),
            ],
        ),
    ]
